### ISSUE TITLE
obey Asimov's three laws of robotics

### ISSUE THREAD

**Issue by HarHarLinks** [Gjum/Bat#15]
1. A robot may not injure a human being or, through inaction, allow a human being to come to harm.
2. A robot must obey the orders given it by human beings, except where such orders would conflict with the First Law.
3. A robot must protect its own existence as long as such protection does not conflict with the First or Second Law.

**Comment by Gjum** [comment]
2. gets implemented via [Tasks](https://github.com/Gjum/Bat/milestones/Tasks) and [Player Interaction and Commands](https://github.com/Gjum/Bat/milestones/Player%20Interaction%20&%20Commands), 3. via [Passive Tasks](https://github.com/Gjum/Bat/milestones/Passive%20Tasks).
1. would prevent a `kill <player>` command, do we want that?

**Comment by Gjum** [comment]
https://www.youtube.com/watch?v=7PKx3kS7f4A
