### ISSUE TITLE
fe_type

### ISSUE THREAD

**Issue by tsenapathi** [Gjum/Bat#24]
Hi,
I have been trying to run some of the examples.
Gettting an error 
```
    if fe_type == 'rest':
NameError: name 'fe_type' is not defined
```
Where should I specify the fe_type varible?

**Comment by Gjum** [comment]
There's no `fe_type` in this project, can you post the full stack trace and also what command/code you're running exactly?

Please also note that Bat and SpockBot are not being worked on anymore and only work with Minecraft 1.8, my focus has been on [another CLI bot](https://github.com/Gjum/Botlin) recently.
